title: Grégoire de Bisschop
description: Research interests and publications
baseurl: ""
url: "https://gdebissc.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
show_excerpts: false
